#!/usr/bin/env python3
"""Build drive-grid.js: drive times from HOME to a lat/lng grid, plus to every built-in spot.

One-off, offline step. Uses the public OSRM demo server (OpenStreetMap roads, free-flow, no traffic),
politely: <=100 coordinates per request and ~1 request per second. Re-run only when HOME or spots change.

    python3 tools/build-drive-grid.py
"""
import json, re, subprocess, time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOME = (-37.788, 144.93)                   # Flemington centre (lat, lng), suburb-level on purpose. Keep in sync with spots.js
SOUTH, NORTH, WEST, EAST = -39.2, -35.6, 142.2, 148.6
DLAT, DLNG = 0.06, 0.075                   # ~6.5 km cells
SNAP_LIMIT_M = 3000                        # grid points >3 km from any road (sea, bay, deep bush) are left blank
OFFROAD_KMH = 30                           # the last bit from road to point is counted at a slow 30 km/h
BATCH = 99                                 # + 1 source = 100 coords per request
URL = "https://router.project-osrm.org/table/v1/driving/{coords}?sources=0&annotations=duration"
UA = "casual-angling-grid/1.0 (personal project; one-off build)"


def table(points):
    """Durations (s) and snap distances (m) from HOME to each (lat, lng)."""
    coords = ";".join(f"{lng:.5f},{lat:.5f}" for lat, lng in [HOME, *points])
    # curl rather than urllib: macOS's bundled Python has an SSL stack too old for the OSRM server.
    for attempt in range(4):
        try:
            out = subprocess.run(["curl", "-sS", "-m", "60", "-A", UA, URL.format(coords=coords)],
                                 capture_output=True, text=True, check=True).stdout
            d = json.loads(out)
            if d.get("code") != "Ok":
                raise RuntimeError(d.get("code"))
            return d["durations"][0][1:], [x["distance"] for x in d["destinations"][1:]]
        except Exception as e:  # rate limits or blips: back off and retry
            wait = 3 * (attempt + 1)
            print(f"  retry in {wait}s ({e})")
            time.sleep(wait)
    raise SystemExit("OSRM failed repeatedly; try again later.")


def minutes(dur, snap):
    if dur is None or snap > SNAP_LIMIT_M:
        return -1
    return round(dur / 60 + (snap / 1000) / OFFROAD_KMH * 60)


def main():
    rows = round((NORTH - SOUTH) / DLAT) + 1
    cols = round((EAST - WEST) / DLNG) + 1
    pts = [(NORTH - r * DLAT, WEST + c * DLNG) for r in range(rows) for c in range(cols)]
    print(f"Grid {rows}x{cols} = {len(pts)} points, {-(-len(pts) // BATCH)} requests")

    data = []
    for i in range(0, len(pts), BATCH):
        durs, snaps = table(pts[i:i + BATCH])
        data += [minutes(d, s) for d, s in zip(durs, snaps)]
        print(f"  {min(i + BATCH, len(pts))}/{len(pts)}")
        time.sleep(1.1)

    # Built-in spots, read from spots.js so the pins and the overlay use the same numbers.
    src = (ROOT / "spots.js").read_text()
    spots = re.findall(r"id: '([\w-]+)', name: '[^']*', lat: (-?[\d.]+), lng: (-?[\d.]+)", src)
    spot_times = {}
    for i in range(0, len(spots), BATCH):
        chunk = spots[i:i + BATCH]
        durs, _ = table([(float(lat), float(lng)) for _, lat, lng in chunk])
        for (sid, _, _), d in zip(chunk, durs):
            if d is not None:
                spot_times[sid] = round(d / 60)
        time.sleep(1.1)

    grid = {
        "source": "OSRM (OpenStreetMap), free-flow, no traffic",
        "built": time.strftime("%Y-%m-%d"),
        "home": {"lat": HOME[0], "lng": HOME[1]},
        "north": NORTH, "south": SOUTH, "west": WEST, "east": EAST,
        "rows": rows, "cols": cols, "data": data, "spots": spot_times,
    }
    out = ROOT / "drive-grid.js"
    out.write_text("// Generated by tools/build-drive-grid.py — do not hand-edit.\n"
                   f"window.DRIVE_GRID = {json.dumps(grid, separators=(',', ':'))};\n")
    reach = sum(1 for v in data if v >= 0)
    print(f"Wrote {out.name}: {reach}/{len(data)} reachable cells, {len(spot_times)} spots timed")


if __name__ == "__main__":
    main()
